# Generated by Django 5.2.13 on 2026-05-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_instructor_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='customer_app.choice'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.learner')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_app.enrollment'),
            preserve_default=False,
        ),
    ]
